PhoneBook.Endpoints.WebUI/Models/ErrorViewModel.cs
namespace PhoneBook.Endpoints.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PhoneBook.Endpoints.WebUI/Models/Persons/AddPersonViewModel.cs
using PhoneBook.Core.Resources.Resources;
using System.ComponentModel.DataAnnotations;

namespace PhoneBook.Endpoints.WebUI.Models.Persons
{
    public class AddPersonViewModel
    {
        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.FirstName)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.LastName)]
        public string LastName { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.Email)]
        public string Email { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.Address)]
        public string Address { get; set; }


        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.PhoneNumber)]
        public string PhoneNumber { get; set; }

    }
}

PhoneBook.Endpoints.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Endpoints.WebUI.Models;
using System.Diagnostics;

namespace PhoneBook.Endpoints.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PhoneBook.Endpoints.WebUI/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using PhoneBook.Core.Domain.Persons.Commands;
using PhoneBook.Core.Domain.Persons.Entities;
using PhoneBook.Core.Domain.Persons.Queries;
using PhoneBook.Endpoints.WebUI.Models.Persons;
using PhoneBook.Framework.Commands;
using PhoneBook.Framework.Queries;
using PhoneBook.Framework.Resources;
using PhoneBook.Framework.Web;

namespace PhoneBook.Endpoints.WebUI.Controllers
{
    public class PersonsController : BaseController
    {
        public PersonsController(CommandDispatcher commandDispatcher,
            QueryDispatcher queryDispatcher, IResourceManager resourceManager)
            : base(commandDispatcher, queryDispatcher, resourceManager)
        {
        }

        public IActionResult Index()
        {
            var allPersons = _queryDispatcher.Dispatch<List<Person>>(new AllPersonQuery());
            return View(allPersons);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddPersonViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _commandDispatcher.Dispatch(new AddPersonCommand
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Address = model.Address,
                    PhoneNumber = model.PhoneNumber
                });

                if (result.IsSuccess)
                    return RedirectToAction("Index");

                ModelState.AddModelError("", result.Message);
                foreach (string item in result.Errors)
                {
                    ModelState.AddModelError("", item);
                }
            }
            return View(model);
        }
    }
}

PhoneBook.Endpoints.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PhoneBook.Endpoints.WebUI/Views/Persons/Add.cshtml
@inject IResourceManager _resourceManager
@model PhoneBook.Endpoints.WebUI.Models.Persons.AddPersonViewModel
@{
    ViewData["Title"] = _resourceManager[SharedResource.AddContact];
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.AddContact]
                </h3>
            </div>
            <div class="card-body">
                <form asp-controller="Persons" asp-action="Add" method="post">
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input type="text" class="form-control" asp-for="FirstName">
                        <span asp-validation-for="FirstName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input type="text" class="form-control" asp-for="LastName">
                        <span asp-validation-for="LastName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input type="text" class="form-control" asp-for="Email">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address"></label>
                        <input type="text" class="form-control" asp-for="Address">
                        <span asp-validation-for="Address"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber"></label>
                        <input type="text" class="form-control" asp-for="PhoneNumber">
                        <span asp-validation-for="PhoneNumber"></span>
                    </div>

                    <button type="submit" class="btn btn-primary">@_resourceManager[SharedResource.Save]</button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
    {
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
}

PhoneBook.Endpoints.WebUI/Views/Persons/Index.cshtml
@model List<PhoneBook.Core.Domain.Persons.Entities.Person>
@inject IResourceManager _resourceManager
@{
    ViewData["Title"] = _resourceManager[SharedResource.Contacts];
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.Contacts]
                </h3>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-light">
                    @if (Model.Any())
                    {
                        foreach (var item in Model)
                        {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.Phone.PhoneNumber
                        </td>
                    </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            @_resourceManager[SharedResource.NoDate]
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

PhoneBook.Endpoints.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhoneBook.Endpoints.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PhoneBook.Endpoints.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneBook.Endpoints.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">PhoneBook</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PhoneBook.Endpoints.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>